---

- name: Gather package facts
  ansible.builtin.package_facts:

- name: Include installation.yml
  ansible.builtin.include_tasks: installation.yml

- name: Include installation.yml specific for architecture
  ansible.builtin.include_tasks: "installation-{{ ansible_facts['architecture'] }}.yml"

- name: Gather package facts again after the installation phase
  ansible.builtin.package_facts:

- name: Include configuration.yml
  ansible.builtin.include_tasks: '{{ ansible_facts["distribution"] }}/{{ sap_hana_preconfigure_assert | ternary("assert-","") ) }}configuration.yml'

# allow a reboot at the end of the preconfigure role
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
