---
- name: "Set needs-restarting command in case of RHEL 7"
  ansible.builtin.set_fact:
    __sap_hana_preconfigure_fact_needs_restarting_command: "needs-restarting -r"
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version == '7'

- name: "Set needs-restarting command in case of RHEL 8 or RHEL 9, except RHEL 8.0"
  ansible.builtin.set_fact:
    __sap_hana_preconfigure_fact_needs_restarting_command: "yum needs-restarting -r"
  when:
    - ansible_os_family == 'RedHat'
    - (ansible_distribution_major_version == '8' or
         ansible_distribution_major_version == '9'
      )
    - ansible_distribution_version != '8.0'

- name: "Set customized needs-restarting command in case of RHEL 8.0"
  ansible.builtin.set_fact:
    __sap_hana_preconfigure_fact_needs_restarting_command: "_IKRNL=$(rpm -q --last kernel | awk 'NR==1{sub(/kernel-/,\"\"); print $1}'); _CKRNL=$(uname -r); if [ ${_IKRNL} != ${_CKRNL} ]; then exit 1; else exit 0; fi"
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_version == '8.0'

- name: Display the command for checking a reboot requirement
  ansible.builtin.debug:
    var: __sap_hana_preconfigure_fact_needs_restarting_command

# Reason for noqa: The command to be executed might contain pipes
- name: Determine if system needs to be restarted # noqa command-instead-of-shell
  ansible.builtin.shell: "{{ __sap_hana_preconfigure_fact_needs_restarting_command }}"
  register: __sap_hana_preconfigure_register_needs_restarting
  ignore_errors: true
  changed_when: false
  check_mode: false

- name: Display the output of the reboot requirement check
  ansible.builtin.debug:
    var: __sap_hana_preconfigure_register_needs_restarting