---

- name: Include OS specific vars, specific
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution.split("_")[0] }}_{{ ansible_distribution_version }}.yml'
    - '{{ ansible_distribution.split("_")[0] }}_{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_os_family }}.yml'


- name: Prepend filename with assert string if role is run in assert mode
  ansible.builtin.set_fact:
    __sap_general_preconfigure_fact_assert_filename_prefix: "assert-"
  when: sap_general_preconfigure_assert | d(false)

# required for installation and configuration tasks:
- name: Gather package facts
  ansible.builtin.package_facts:

- name: Include tasks from 'installation.yml'
  ansible.builtin.include_tasks: '{{ item }}/{{ __sap_general_preconfigure_fact_assert_filename_prefix }}installation.yml'
  when: sap_general_preconfigure_config_all | d(true) or sap_general_preconfigure_installation | d(false)
  with_first_found:
    - '{{ ansible_distribution.split("_")[0] }}'
    - '{{ ansible_distribution }}'
    - '{{ ansible_os_family }}.yml'

- name: Gather package facts again after the installation phase
  ansible.builtin.package_facts:

- name: Include tasks from 'configuration.yml'
  ansible.builtin.include_tasks: '{{ item }}/{{ __sap_general_preconfigure_fact_assert_filename_prefix }}configuration.yml'
  when: sap_general_preconfigure_config_all | d(true) or sap_general_preconfigure_configuration | d(false)
  with_first_found:
    - '{{ ansible_distribution.split("_")[0] }}'
    - '{{ ansible_distribution }}'
    - '{{ ansible_os_family }}.yml'

# allow a reboot at the end of the preconfigure role
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
