---

# Default parameter file for sysctl settings according to SAP NOTE 2382421
__sap_hana_preconfigure_etc_sysctl_saphana_conf: /etc/sysctl.d/sap_hana.conf

# Default parameter file for sysctl settings according to SAP NOTE 3024346
__sap_hana_preconfigure_etc_sysctl_netapp_hana_conf: /etc/sysctl.d/91-NetApp-HANA.conf

# SELinux is already configured in role sap_general_preconfigure:
#__sap_hana_preconfigure_selinux_state: disabled

__sap_hana_preconfigure_tuned_profile: 'sap-hana'

__sap_hana_preconfigure_run_grub2_mkconfig: yes


---

# supported RHEL 7 minor releases for SAP HANA:
__sap_hana_preconfigure_supported_rhel_minor_releases:
  - "7.6"
  - "7.7"
  - "7.9"
  - "8.0"
  - "8.1"
  - "8.2"
  - "8.4"
  - "8.6"

# required repos for RHEL 7:
__sap_hana_preconfigure_req_repos:
  x86_64:
    7:
      - "rhel-7-server-e4s-rpms"
      - "rhel-sap-hana-for-rhel-7-server-e4s-rpms"
    "7.6":
      - "rhel-7-server-e4s-rpms"
      - "rhel-sap-hana-for-rhel-7-server-e4s-rpms"
    redhat_7_7:
      - "rhel-7-server-e4s-rpms"
      - "rhel-sap-hana-for-rhel-7-server-e4s-rpms"
    redhat_7_8:
      - "rhel-7-server-rpms"
      - "rhel-sap-hana-for-rhel-7-server-rpms"
    redhat_7_9:
      - "rhel-7-server-rpms"
      - "rhel-sap-hana-for-rhel-7-server-rpms"
    "8.0":
      - "rhel-8-for-x86_64-baseos-e4s-rpms"
      - "rhel-8-for-x86_64-appstream-e4s-rpms"
      - "rhel-8-for-x86_64-sap-solutions-e4s-rpms"
    "8.1":
      - "rhel-8-for-x86_64-baseos-e4s-rpms"
      - "rhel-8-for-x86_64-appstream-e4s-rpms"
      - "rhel-8-for-x86_64-sap-solutions-e4s-rpms"
    "8.2":
      - "rhel-8-for-x86_64-baseos-e4s-rpms"
      - "rhel-8-for-x86_64-appstream-e4s-rpms"
      - "rhel-8-for-x86_64-sap-solutions-e4s-rpms"
    "8.3":
      - "rhel-8-for-x86_64-baseos-rpms"
      - "rhel-8-for-x86_64-appstream-rpms"
      - "rhel-8-for-x86_64-sap-solutions-rpms"
    "8.4":
      - "rhel-8-for-x86_64-baseos-e4s-rpms"
      - "rhel-8-for-x86_64-appstream-e4s-rpms"
      - "rhel-8-for-x86_64-sap-solutions-e4s-rpms"
    "8.5":
      - "rhel-8-for-x86_64-baseos-rpms"
      - "rhel-8-for-x86_64-appstream-rpms"
      - "rhel-8-for-x86_64-sap-solutions-rpms"
    "8.6":
      - "rhel-8-for-x86_64-baseos-rpms"
      - "rhel-8-for-x86_64-appstream-rpms"
      - "rhel-8-for-x86_64-sap-solutions-rpms"
    "8.7":
      - "rhel-8-for-x86_64-baseos-rpms"
      - "rhel-8-for-x86_64-appstream-rpms"
      - "rhel-8-for-x86_64-sap-solutions-rpms"
    "8.8":
      - "rhel-8-for-x86_64-baseos-rpms"
      - "rhel-8-for-x86_64-appstream-rpms"
      - "rhel-8-for-x86_64-sap-solutions-rpms"
    "8.9":
      - "rhel-8-for-x86_64-baseos-rpms"
      - "rhel-8-for-x86_64-appstream-rpms"
      - "rhel-8-for-x86_64-sap-solutions-rpms"
    "8.10":
      - "rhel-8-for-x86_64-baseos-rpms"
      - "rhel-8-for-x86_64-appstream-rpms"
      - "rhel-8-for-x86_64-sap-solutions-rpms"
  ppc64le:
    redhat_7_6:
      - "rhel-7-for-power-le-e4s-rpms"
      - "rhel-sap-hana-for-rhel-7-for-power-le-e4s-rpms"
    redhat_7_7:
      - "rhel-7-for-power-le-e4s-rpms"
      - "rhel-sap-hana-for-rhel-7-for-power-le-e4s-rpms"
    redhat_7_9:
      - "rhel-7-for-power-le-rpms"
      - "rhel-sap-hana-for-rhel-7-for-power-le-rpms"
    "8.0":
      - "rhel-8-for-ppc64le-baseos-e4s-rpms"
      - "rhel-8-for-ppc64le-appstream-e4s-rpms"
      - "rhel-8-for-ppc64le-sap-solutions-e4s-rpms"
    "8":
      - "rhel-8-for-ppc64le-baseos-e4s-rpms"
      - "rhel-8-for-ppc64le-appstream-e4s-rpms"
      - "rhel-8-for-ppc64le-sap-solutions-e4s-rpms"

# required SAP notes for RHEL 8:
__sap_hana_preconfigure_sapnotes_versions:
  x86_64:
    "7":
      - { number: '2009879', version: '28' }
      - { number: '2292690', version: '38' }
      - { number: '2382421', version: '40' }
      - { number: '3024346', version: '3' }
    "8":
      - { number: '2777782', version: '33' }
      - { number: '2382421', version: '40' }
      - { number: '3024346', version: '3' }
  ppc64le:
    "7":
      - { number: '2009879', version: '28' }
      - { number: '2055470', version: '85' }
      - { number: '2292690', version: '38' }
      - { number: '2382421', version: '40' }
      - { number: '3024346', version: '3' }
    "8":
      - { number: '2055470', version: '87' }
      - { number: '2777782', version: '33' }
      - { number: '2382421', version: '40' }
      - { number: '3024346', version: '3' }



__sap_hana_preconfigure_sapnotes_versions_list: >
  "{{ __sap_hana_preconfigure_sapnotes_versions[ansible_facts['architecture']] }}"

# In SAP Note 2235581, certain minimal required packages for the different RHEL 7 minor releases are listed.
# The following will assign them properly to __sap_hana_preconfigure_min_pkgs.
# If variable __sap_hana_preconfigure_min_packages_VERSION is not defined,
# variable __sap_hana_preconfigure_min_pkgs will be undefined as well.

__sap_hana_preconfigure_min_packages:
  x86_64:
    "7.2":
      - name: 'kernel'
        version: '3.10.0-327.62.4.el7'
      - [ 'systemd', '219-19.el7_2.4' ]
    "7.3":
      - [ 'kernel', '3.10.0-514.36.5.el7' ]
      - [ 'glibc', '2.17-157.el7_3.5' ]
      - [ 'tuned-profiles-sap-hana', '2.7.1-3.el7_3.3' ]
    "7.4":
# Attention: SAP note 2812427 requires more recent package kernel-3.10.0-693.58.1, covered by role sap_general_preconfigure
      - [ 'kernel', '3.10.0-693.11.6.el7' ]
      - [ 'tuned-profiles-sap-hana', '2.8.0-5.el7_4.2' ]
    "7.5": []
    "7.6":
# Attention: SAP note 2812427 requires more recent package kernel-3.10.0-957.35.1, covered by role sap_general_preconfigure
      - [ 'kernel', '3.10.0-957.1.3.el7' ]
# SAP note 2292690:
    "7.7":
      - [ 'kernel', '3.10.0-1062.21.1.el7' ]
    "7.8": []
    "7.9":
      - [ 'kernel', '3.10.0-1160.11.1.el7' ]

  ppc64le:
    "7.2":
      - [ 'kernel', '3.10.0-327.62.4.el7' ]
      - [ 'systemd', '219-19.el7_2.4' ]
    "7.3":
      - [ 'kernel', '3.10.0-514.36.5.el7' ]
      - [ 'glibc', '2.17-157.el7_3.5' ]
      - [ 'tuned-profiles-sap-hana', '2.7.1-3.el7_3.3' ]
    "7.4":
      - [ 'kernel', '3.10.0-693.11.6.el7' ]
      - [ 'tuned-profiles-sap-hana', '2.8.0-5.el7_4.2' ]
    "7.5": []
    "7.6":
      - [ 'kernel', '3.10.0-957.1.3.el7' ]
    "7.7":
      - [ 'kernel', '3.10.0-1062.26.1.el7' ]
    "7.8": []
    "7.9":
      - [ 'kernel', '3.10.0-1160.11.1.el7' ]

__sap_hana_preconfigure_min_pkgs_list: >
  "{{__sap_hana_preconfigure_min_packages
  [ansible_facts['architecture']]
  [ansible_facts['distribution_version']] }}"

__sap_hana_preconfigure_packages:
  "7":
    # SAP note 2009879:
    - chrony
    - xfsprogs
    - libaio
    - net-tools
    - bind-utils
    - gtk2
    - libicu
    - xulrunner
    - tcsh
    - sudo
    - libssh2
    - expect
    - cairo
    - graphviz
    - iptraf-ng
    - krb5-workstation
    - krb5-libs
    - libpng12
    - nfs-utils
    - lm_sensors
    - rsyslog
    - openssl
    - PackageKit-gtk3-module
    - libcanberra-gtk2
    - libtool-ltdl
    - xorg-x11-xauth
    - numactl
    - tuned
    # SAP note 2292690:
    - tuned-profiles-sap-hana
    - compat-sap-c++-5
    # SAP note 2455582:
    - compat-sap-c++-6
    # SAP note 2593824:
    - compat-sap-c++-7
    - libatomic
    # Likely required for future HANA 2.0 versions:
    - compat-sap-c++-9
  "8":
    # SAP NOTE 2772999:
    - expect
    # package graphwiz: graph visualization toos, for supportability)
    - graphviz
    # package iptraf-ng: TCP/IP network monitor, for supportability)
    - iptraf-ng
    - krb5-workstation
    - libatomic
    - libcanberra-gtk2
    - libibverbs
    - libicu
    # package libpng12: only needed by the SAP HANA 1 installer
    #  - libpng12
    # package libssh2: only needed for scaleout installation of SAP HANA 2.0 before SPS04 rev 48.02 or before SPS05 rev 51
    #  - libssh2
    # package lm-sensors: TCP/IP network monitor, for supportability)
    - lm_sensors
    # package nfs-utils: support utilities for NFS, for supportability)
    - nfs-utils
    - numactl
    - PackageKit-gtk3-module
    - xorg-x11-xauth
    - bind-utils
    - cairo
    - libaio
    - krb5-libs
    # package net-tools: contains deprecated command line network interface management tools
    - net-tools
    - openssl
    - rsyslog
    - sudo
    - xfsprogs
    # package gtk2: only needed if the SAP HANA installation tools hdblcmgui and hdbsetup are used
    - gtk2
    - libtool-ltdl
    # SAP NOTE 2777782:
    - tuned-profiles-sap-hana

# libtool-ltdl: See https://answers.sap.com/questions/476177/hana-db-installation-ended-with-exit-code-127.html
# This is required since HANA 2 SPS 03, and so we always install it.

__sap_hana_preconfigure_ibm_power_repo_url: 'http://public.dhe.ibm.com/software/server/POWER/Linux/yum/download/ibm-power-repo-latest.noarch.rpm'

# As per https://www14.software.ibm.com/support/customercare/sas/f/lopdiags/home.html :
__sap_hana_preconfigure_required:
  ppc64le:
    "7":
      - librtas
      - src
      - rsct.core.utils
      - rsct.core
      - rsct.basic
      - rsct.opt.storagerm
      - devices.chrp.base.ServiceRM
      - DynamicRM
      - ncurses-libs
      - readline
      - sqlite
      - sg3_utils
      - libgcc
      - libstdc++
      - zlib
      - iprutils
      - lsvpd
      - libvpd
      - libservicelog
      - servicelog
      - powerpc-utils
      - powerpc-utils-python
      - ppc64-diag
      - IBMinvscout
    "8":
      - librtas
      - src
      - rsct.core.utils
      - rsct.core
      - rsct.basic
      - rsct.opt.storagerm
      - devices.chrp.base.ServiceRM
      - DynamicRM
      - ncurses-libs
      - readline
      - sqlite
      - sg3_utils
      - libgcc
      - libstdc++
      - zlib
      - iprutils
      - lsvpd
      - libvpd
      - libservicelog
      - servicelog
      - powerpc-utils
      #  - powerpc-utils-python # this package is no longer available for RHEL 8
      - ppc64-diag
      #  - IBMinvscout # this package is no longer available for RHEL 8


# Network related kernel parameters as set in SAP Note 2382421:
__sap_hana_preconfigure_kernel_parameters_default:
  x86_64:
  # The following two parameter should always be set:
    - { name: net.core.somaxconn, value: 4096 }
    - { name: net.ipv4.tcp_max_syn_backlog, value: 8192 }
  # The following two parameters are automatically set by SAP Host Agent
  #  - { name: net.ipv4.ip_local_port_range, value: "40000 61000" }
  #  - { name: net.ipv4.ip_local_reserved_ports, value: -> SAP NOTE 2477204 }
  # The following two parameters do not work when communicating with hosts behind NAT firewall:
  #  - { name: net.ipv4.tcp_tw_reuse, value: 1 }
  #  - { name: net.ipv4.tcp_tw_recycle, value: 1 }
  # The following parameter should always be set but might not work on Azure (see SAP Note 2382421):
    - { name: net.ipv4.tcp_timestamps, value: 1 }
  # The following parameter should always be set:
    - { name: net.ipv4.tcp_slow_start_after_idle, value: 0 }
  # Tune the next four parameters for low latency system replication:
  #  - { net.ipv4.tcp_wmem, value }
  #  - { net.ipv4.tcp_rmem, value }
  #  - { net.core.wmem_max, value }
  #  - { net.core.rmem_max, value }
  # Should be set correctly already on most systems, according to SAP Note 2382421:
  #  - { net.ipv4.tcp_window_scaling, 1 }
  # The following only applies to HANA 1 <= 122.14 and HANA 2 SPS00.
  # So we do not change the default.
  #  - { name: net.ipv4.tcp_syn_retries, value: 8 }

# Network related kernel parameters for ppc64le:
  ppc64le:
  - { name: net.core.rmem_max, value: 56623104 }
  - { name: net.core.wmem_max, value: 56623104 }
  - { name: net.ipv4.tcp_rmem, value: "65536 262088 56623104" }
  - { name: net.ipv4.tcp_wmem, value: "65536 262088 56623104" }
  - { name: net.ipv4.tcp_mem, value: "56623104 56623104 56623104" }

# Network related kernel parameters for NetApp NFS, as set in SAP Note 3024346:
__sap_hana_preconfigure_kernel_parameters_netapp_nfs:
  - { name: net.core.rmem_max, value: 16777216 }
  - { name: net.core.wmem_max, value: 16777216 }
  - { name: net.ipv4.tcp_rmem, value: "4096 131072 16777216" }
  - { name: net.ipv4.tcp_wmem, value: "4096 16384 16777216" }
  - { name: net.core.netdev_max_backlog, value: 300000 }
# already set in SAP note 2382421:
#  - { name: net.ipv4.tcp_slow_start_after_idle, value: 0 }
  - { name: net.ipv4.tcp_no_metrics_save, value: 1 }
  - { name: net.ipv4.tcp_moderate_rcvbuf, value: 1 }
  - { name: net.ipv4.tcp_window_scaling, value: 1 }
# already set in SAP note 2382421:
#  - { name: net.ipv4.tcp_timestamps, value: 1 }
  - { name: net.ipv4.tcp_sack, value: 1 }

# yamllint disable rule:commas rule:colons
__sap_hana_preconfigure_packages_and_services:
  abrtd:     { pkg: 'abrt',            svc: 'abrtd',     systemd_enabled: 'no', systemd_state: 'stopped', svc_status: 'disabled', svc_state: 'inactive' }
  abrt-ccpp: { pkg: 'abrt-addon-ccpp', svc: 'abrt-ccpp', systemd_enabled: 'no', systemd_state: 'stopped', svc_status: 'disabled', svc_state: 'inactive' }
  numad:     { pkg: 'numad',           svc: 'numad',     systemd_enabled: 'no', systemd_state: 'stopped', svc_status: 'disabled', svc_state: 'inactive' }
  kdump:     { pkg: 'kexec-tools',     svc: 'kdump',     systemd_enabled: 'no', systemd_state: 'stopped', svc_status: 'disabled', svc_state: 'inactive' }
  firewalld: { pkg: 'firewalld',       svc: 'firewalld', systemd_enabled: 'no', systemd_state: 'stopped', svc_status: 'disabled', svc_state: 'inactive' }
# yamllint enable rule:commas rule:colons


__sap_hana_preconfigure_notes_packages:
  2578899:
    - libssh2-1
    - libopenssl1_1
    - systat
    - uuidd
    - insserv-compat
  2777782:
    - libzopenssl1_1
    - libssh2-1
  