---
# The SAP ID must follow a strict format and not use reserved special values
# TODO: This check may be better placed in a SAP role earlier in the chain...
- name: "SAP HA Prepare Pacemaker - Validate SAP System ID"
  ansible.builtin.assert:
    that:
      - sap_ha_pacemaker_cluster_hana_sid is sap.sap_operations.valid_sid
